### ISSUE TITLE
support for fields.Dict()

### ISSUE THREAD

**Issue by rcoh** [marshmallow-code/django-rest-marshmallow#11]
Seems to exist in marshmallow but not in django-rest-marshmallow. Is there an easy workaround? I want to have a dict of string->string pairs in my schema

**Comment by sloria** [comment]
django-rest-marshmallow just imports the fields module from marshmallow, so `fields.Dict` should exist. What version of marshmallow do you have installed? You may need to update it.

**Comment by sloria** [comment]
Closing this for now, as it has gone stale. Feel free to reopen if you run into this again.
