### ISSUE TITLE
Transfer to marshmallow-code?

### ISSUE THREAD

**Issue by lovelydinosaur** [marshmallow-code/django-rest-marshmallow#14]
@sloria - Having a bit of a clean out and wondered if we should consider transferring this repo to your marshallow-code org?

**Comment by sloria** [comment]
I am good with that.

**Comment by lovelydinosaur** [comment]
Okay, looks like I'd need create-repo permissions in that org in order to do the transfer.

![screen shot 2017-07-18 at 14 12 16](https://user-images.githubusercontent.com/647359/28318545-200acd4a-6bc3-11e7-8ac3-61a31ffc1aec.png)

Could do that and then remove me after, or else just punt on it.

**Comment by sloria** [comment]
The easiest way would be to transfer to my personal account (sloria), then I'll do the transfer to marshmallow-code.

**Comment by lovelydinosaur** [comment]
Good plan

**Comment by lovelydinosaur** [comment]
You'll need to delete your fork first.

**Comment by sloria** [comment]
Done.

**Comment by lovelydinosaur** [comment]
Transfer request sent. Thanks @sloria!

**Comment by sloria** [comment]
Done. Thanks.

**Comment by sloria** [comment]
@tomchristie How are docs built? They are currently out of date.

**Comment by lovelydinosaur** [comment]
Some stuff here: https://github.com/marshmallow-code/django-rest-marshmallow#documentation

To deploy: `mkdocs gh-deploy`

**Comment by lovelydinosaur** [comment]
Tho very welcome to bring 'em into line with your other projects if wanted.

**Comment by sloria** [comment]
Thanks @tomchristie . That worked. I think the current docs work just fine. No need to change what isn't broke =).
