### ISSUE TITLE
How to use same schema for both Django and non-Django code?

### ISSUE THREAD

**Issue by fingon** [marshmallow-code/django-rest-marshmallow#5]
Currently, it seems you have to use rest_marshmalow.\* to replace marshmallow stuff. However, what if I want to use same schema in both Django- and non-Django code?

I see mostly bad options, e.g. use mostly Django version, and then do creative search-n-replace (rest_marshmallow => marshmallow) and cutting (redundant create/update methods in the schema objects).

This is more of a feature request than a bug I guess though..

**Comment by danbenedicto** [comment]
I was wondering the same thing. I understand that this would add more boilerplate/another layer, but what about just creating a generic SchemaSerializer?

```
from marshmallow import Schema, fields
from rest_marshmallow import SchemaSerializer

class CustomerSchema(Schema):
    name = fields.String()
    email = fields.Email()
    created_at = fields.DateTime()

class CustomerSerializer(SchemaSerializer):
    schema = CustomerSchema
```

Then SchemaSerializer could just delegate the serializer interface methods to the schema.

**Comment by sloria** [comment]
Along the lines of what @danbenedicto is suggesting, I wonder if we could implement a factory that creates a DRF serializer given a vanilla marshmallow Schema.

``` python
from marshmallow import Schema, fields
from rest_marshmallow import create_serializer

class CustomerSchema(Schema):
    name = fields.String()
    email = fields.Email()
    created_at = fields.DateTime()

CustomerSerializer = create_serializer(CustomerSchema)
```

I welcome any feedback on this.

**Comment by sloria** [comment]
For my example above, you might be able to get away with something as simple as:

``` python
from rest_marshmallow import Schema as DRFSchema

def create_serializer(schema_cls, attrs=None):
    name = schema_cls.__name__.replace('Schema', '') + 'Serializer'
    return type(name, (schema_cls, DRFSchema), attrs or {})
```

**Comment by sloria** [comment]
I'm going to hold off on adding any implementation to this package. For anyone that needs this, the helper function above should suffice.

Closing for now.
