### ISSUE TITLE
get_attribute() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by codespresso** [marshmallow-code/django-rest-marshmallow#6]
I am getting this error. Is it me doing something wrong or is it a bug. The problem seems to be happening because its using the get_attribute method in Field class of rest_framework and not the one defined in
BaseSchema class of Marshmallow.

**Comment by sloria** [comment]
@codespresso Could you post code to reproduce your bug? Also, what version of DRF and marshmallow are you using?

**Comment by sloria** [comment]
Looks like tests are failing for marshmallow>=2.0. I've sent a PR to fix this bug.
